services:
  - type: web
    name: laurea-party-game
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ADMIN_KEY
        value: "110201"
      - key: BOSS_KEY
        value: "04112017"
      - key: PUBLIC_URL
        value: ""
